"""
Azure Communication Services Solution Architecture Diagram
Generated by diagram-generator agent
Date: 2024-12-10

Prerequisites:
- pip install diagrams
- Graphviz installed (apt-get install graphviz / brew install graphviz / choco install graphviz)

Generate PNG: python architecture.py
"""

from diagrams import Diagram, Cluster, Edge, Node
from diagrams.azure.compute import FunctionApps, AppServices
from diagrams.azure.database import CosmosDb
from diagrams.azure.storage import StorageAccounts
from diagrams.azure.security import KeyVaults
from diagrams.azure.integration import EventGridTopics, ServiceBus
from diagrams.azure.devops import ApplicationInsights
from diagrams.azure.analytics import LogAnalyticsWorkspaces
from diagrams.azure.identity import ManagedIdentities
from diagrams.azure.general import Usericon, Mobile
from diagrams.onprem.client import Users
from diagrams.generic.device import Mobile as MobileDevice
from diagrams.generic.network import Firewall

# Diagram configuration for professional output
graph_attr = {
    "fontsize": "28",
    "bgcolor": "white",
    "pad": "0.5",
    "splines": "ortho",
    "nodesep": "0.8",
    "ranksep": "1.2"
}

node_attr = {
    "fontsize": "12"
}

edge_attr = {
    "fontsize": "10"
}

with Diagram(
    "Azure Communication Services Solution",
    show=False,
    direction="TB",
    filename="acs_solution_architecture",
    graph_attr=graph_attr,
    node_attr=node_attr,
    edge_attr=edge_attr,
    outformat="png"
):
    # External users/clients
    with Cluster("Clients"):
        web_user = Users("Web Users")
        mobile_user = MobileDevice("Mobile Apps")
    
    # External communication targets
    with Cluster("External Endpoints"):
        pstn = Firewall("PSTN\n(Phone Network)")
        email_recipients = Users("Email Recipients")
        sms_recipients = MobileDevice("SMS Recipients")
    
    with Cluster("Azure Region - Sweden Central", graph_attr={"bgcolor": "#E6F3FF"}):
        
        with Cluster("Resource Group: rg-acs-solution-prod"):
            
            # Azure Communication Services (represented as custom node)
            with Cluster("Communication Platform", graph_attr={"bgcolor": "#FFF3E6"}):
                # Note: ACS doesn't have a specific icon, using ServiceBus as closest representation
                acs = ServiceBus("Azure Communication\nServices")
                
                with Cluster("Capabilities"):
                    voice_video = FunctionApps("Voice & Video\nCalling")
                    sms_cap = FunctionApps("SMS")
                    chat_cap = FunctionApps("Chat")
                    email_cap = FunctionApps("Email")
            
            # Email Service
            with Cluster("Email Infrastructure", graph_attr={"bgcolor": "#F3E6FF"}):
                email_service = ServiceBus("Email Service")
                email_domain = StorageAccounts("Azure Managed\nDomain")
            
            # Event handling
            with Cluster("Event Processing", graph_attr={"bgcolor": "#E6FFE6"}):
                event_grid = EventGridTopics("Event Grid\nTopics")
                event_handler = FunctionApps("Event Handler\nFunction")
            
            # Security & Secrets
            with Cluster("Security", graph_attr={"bgcolor": "#FFE6E6"}):
                key_vault = KeyVaults("Key Vault")
                managed_id = ManagedIdentities("Managed\nIdentity")
            
            # Monitoring
            with Cluster("Observability", graph_attr={"bgcolor": "#FFFFCC"}):
                log_analytics = LogAnalyticsWorkspaces("Log Analytics\nWorkspace")
                app_insights = ApplicationInsights("Application\nInsights")
            
            # Application Layer (optional)
            with Cluster("Application Tier (Optional)", graph_attr={"bgcolor": "#F0F0F0"}):
                app_service = AppServices("Web App /\nAPI Backend")
                func_app = FunctionApps("Azure Functions\n(Serverless)")
            
            # Data Layer (optional)
            with Cluster("Data Layer (Optional)", graph_attr={"bgcolor": "#E6F0FF"}):
                cosmos = CosmosDb("Cosmos DB\n(Chat History)")
                storage = StorageAccounts("Blob Storage\n(Recordings)")
    
    # === Connections ===
    
    # Client connections
    web_user >> Edge(label="WebRTC/REST") >> app_service
    mobile_user >> Edge(label="SDK") >> app_service
    
    # Application to ACS
    app_service >> Edge(label="ACS SDK") >> acs
    func_app >> Edge(label="ACS SDK") >> acs
    
    # ACS internal connections
    acs >> voice_video
    acs >> sms_cap
    acs >> chat_cap
    acs >> email_cap
    
    # Email flow
    email_cap >> email_service
    email_service >> email_domain
    email_domain >> Edge(label="SMTP") >> email_recipients
    
    # SMS flow
    sms_cap >> Edge(label="SMS") >> sms_recipients
    
    # Voice flow
    voice_video >> Edge(label="PSTN") >> pstn
    
    # Event Grid connections
    acs >> Edge(label="Events", style="dashed") >> event_grid
    email_service >> Edge(label="Delivery Events", style="dashed") >> event_grid
    event_grid >> event_handler
    
    # Security connections
    app_service >> Edge(label="Secrets", style="dotted") >> key_vault
    func_app >> Edge(label="Secrets", style="dotted") >> key_vault
    managed_id >> Edge(style="dotted") >> key_vault
    managed_id >> Edge(style="dotted") >> acs
    
    # Monitoring connections
    acs >> Edge(label="Diagnostics", style="dashed", color="orange") >> log_analytics
    email_service >> Edge(style="dashed", color="orange") >> log_analytics
    app_service >> Edge(style="dashed", color="orange") >> app_insights
    func_app >> Edge(style="dashed", color="orange") >> app_insights
    key_vault >> Edge(style="dashed", color="orange") >> log_analytics
    
    # Data connections
    app_service >> Edge(label="Store Chat") >> cosmos
    voice_video >> Edge(label="Recordings") >> storage

print("✅ Diagram generated: acs_solution_architecture.png")
